language: ruby
rvm:
  - rvm 2.1.1
  - rvm 2.1.5
  - rvm 2.2.0
  - rvm 2.2.1
  - rvm 2.2.2

install:
  - bundle

env:
  global:
    - TWILIO_ACCOUNT_SID=TWILIOACCOUNTSID0000
    - TWILIO_AUTH_TOKEN=TWILIOAUTHTOKEN00000
    - TWILIO_NUMBER=+12345555555
    - TWILIO_NUMBER=+12345555556
